/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS3081W auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <gtest/gtest.h>
#include "src/arena.h"
#include "src/entity_type.h"
#include "src/params.h"

 /******************************************************
* TEST FEATURE SetUp
*******************************************************/
class ArenaTest : public ::testing::Test {

 protected:
  virtual void SetUp() {
    arena = new csci3081::Arena();
  }
  virtual void TearDown() {
    delete arena;
  }

  csci3081::Arena * arena;

};

/*******************************************************************************
 * Test Cases
 ******************************************************************************/

TEST_F(ArenaTest, Constructor) {
  EXPECT_EQ(arena->get_x_dim(), X_DIM);
  EXPECT_EQ(arena->get_y_dim(), Y_DIM);
  EXPECT_GE((int)arena->get_entities().size(), 3) << "FAIL: Arena:Constructor - There should be at least 3 entities";
};
